[package]
name = "nix-eval-cache"
version = "0.1.0"
edition = "2021"

[workspace]
exclude = [
  "recordaccess",
]

[[bin]]
name = "nix-eval-cache"
path = "src/main.rs"

[dependencies]
tempfile = "3.3.0"
nix = "0.23.1"
blake2 = "0.10.4"
hex = "0.4.3"
